apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-cluster-ip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app

  template:
    metadata:
      name: my-web-app
      labels: 
        app: my-web-app
    spec:
      containers:
      - name: custom-image
        image: solimanesammosa/solimann
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
